vnet_name= "ddp-test-vnet"
vnet_cidr_blocks = ["10.0.0.0/16"]
subnet_count = 2
subnet_names = ["dev-ddp-sub-dbr-1", "dev-ddp-sub-dbr-2"]
subnet_cidr_blocks = ["10.0.1.0/26", "10.0.7.0/26"]
service_endpoints = ["Microsoft.Sql", "Microsoft.Storage"]
rg_name = "dev-ddp-rg"
rg_region = "East US 2"
databricks_managed_identity_name = "dbr-mi-adls-rw"
adls_storage_account_name = "devddpadls"
dbr_storage_account_name = "dbrstorageacct"
dbr_storage_container_name = "dbrstoragecontainer"
adls_account_tier = "Standard"
adls_account_replication_type = "LRS"
adls_account_kind = "StorageV2"
adls_is_hns_enabled = "true"